# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GKHelpOutApp' do

pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
#pod'NIMSDK', '~> 3.7.0'
pod 'YTKNetwork'
pod 'SDWebImage', '~> 4.2.3'
pod 'TZImagePickerController', '~> 1.9.8'
pod 'IQKeyboardManager'
pod 'Bugly', '~> 2.4.8'
pod 'AvoidCrash', '~> 2.5.2'
pod 'M80AttributedLabel'
pod 'libextobjc', '~> 0.4.1'
pod 'WechatOpenSDK'
pod 'MJExtension'
pod 'PYPhotoBrowser'
pod 'CDZStarsControl'
pod 'JSONModel', '~> 1.7.0'
pod 'UITextView+Placeholder', '~> 1.2.0'
pod 'BlocksKit', '~> 2.2.5'
pod 'DZNEmptyDataSet'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.6'
pod 'DGActivityIndicatorView'
pod 'AlipaySDK-iOS'
pod 'UITextView+Placeholder', '~> 1.2.0'
pod 'BRPickerView'
pod 'ReactiveObjC'
pod 'EBBannerView'
pod 'ZZFLEX'
pod 'TLTabBarController'
pod 'TLKit'
pod 'Reachability', '~> 3.2'

end

target 'GKHelpOutAppUITests' do
    inherit! :search_paths
    # Pods for testing
end


