# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GKHelpOutApp' do

pod 'MJRefresh'
pod 'AFNetworking', '~> 3.0'
pod 'YYKit'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'Masonry'
#pod'NIMSDK', '~> 3.7.0'
pod 'YTKNetwork'
pod 'SDWebImage', '~> 4.2.3'
pod 'TZImagePickerController', '~> 1.9.8'
pod 'IQKeyboardManager'
pod 'Bugly', '~> 2.4.8'
pod 'AvoidCrash', '~> 2.5.2'
pod 'M80AttributedLabel'


end

target 'GKHelpOutAppUITests' do
    inherit! :search_paths
    # Pods for testing
end


